### ISSUE TITLE
Cannot Build for Linux

### ISSUE THREAD

**Issue by Denton-L** [DavidLu1997/ZopperScanAPI#3]
Running `qmake ScanGrader.pro` gives a warning, `RCC: Warning: No resources in 'scangrader.qrc'.`

Running `make` gives the following error:

```
qrc_scangrader.o: In function `qInitResources_scangrader()':
qrc_scangrader.cpp:(.text+0x0): multiple definition of `qInitResources_scangrader()'
qrc_scangrader.o:qrc_scangrader.cpp:(.text+0x0): first defined here
qrc_scangrader.o: In function `qCleanupResources_scangrader()':
qrc_scangrader.cpp:(.text+0x10): multiple definition of `qCleanupResources_scangrader()'
qrc_scangrader.o:qrc_scangrader.cpp:(.text+0x10): first defined here
collect2: error: ld returned 1 exit status
Makefile:248: recipe for target 'ScanGrader' failed
make: *** [ScanGrader] Error 1
```

**Comment by Denton-L** [comment]
Ran a `git bisect`: `c86ef98441b350b1ce7d4ea24c5125a85fcd93d6 is the first bad commit`

**Comment by DavidLu1997** [comment]
@Denton-L is this fixed with your PR?

**Comment by Denton-L** [comment]
No, I have no idea how it breaks...

**Comment by DavidLu1997** [comment]
Crap, I'll fix it soon.

**Comment by DavidLu1997** [comment]
Closing as Cannot Reproduce
